import type { Product, BundlePackage } from "./types";

export const products: Product[] = [
  {
    id: "1",
    name: "Resistance Bands Set Pro",
    price: 299000,
    description:
      "Complete resistance bands set perfect for full-body workouts in small spaces. Includes 5 resistance levels and door anchor.",
    specifications: [
      "Material: Premium latex rubber",
      "Resistance levels: 5 (10-50 lbs)",
      "Length: 48 inches",
      "Includes door anchor and handles",
      "Weight: 2 lbs",
    ],
    benefits: [
      "Full-body strength training",
      "Compact and portable",
      "Suitable for all fitness levels",
      "Joint-friendly resistance",
    ],
    images: [
      "/placeholder.svg?height=400&width=400&text=Resistance+Bands+1",
      "/placeholder.svg?height=400&width=400&text=Resistance+Bands+2",
    ],
    videos: [
      "/placeholder.svg?height=300&width=400&text=Resistance+Bands+Video",
    ],
    category: "Resistance Training",
    sku: "RB-PRO-001",
    inStock: true,
    isFeatured: true,
    relatedPrograms: [
      "Morning Energy Boost",
      "Desk Break Stretches",
      "Full Body Strength",
    ],
  },
  {
    id: "2",
    name: "Adjustable Dumbbells Compact",
    price: 899000,
    description:
      "Space-saving adjustable dumbbells that replace an entire weight set. Perfect for apartment workouts.",
    specifications: [
      "Weight range: 5-25 lbs per dumbbell",
      "Material: Cast iron with rubber coating",
      'Dimensions: 14" x 6" x 6"',
      "Quick-adjust mechanism",
      "Total weight: 50 lbs",
    ],
    benefits: [
      "Replaces multiple dumbbells",
      "Quick weight adjustment",
      "Compact storage",
      "Durable construction",
    ],
    imagesUrl : [
      "/placeholder.svg?height=400&width=400&text=Adjustable+Dumbbells+1",
      "/placeholder.svg?height=400&width=400&text=Adjustable+Dumbbells+2",
    ],
    videos: ["/placeholder.svg?height=300&width=400&text=Dumbbells+Video"],
    category: "Free Weights",
    sku: "AD-COMP-002",
    inStock: true,
    isFeatured: true,
    relatedPrograms: ["Upper Body Power", "Core Strength", "HIIT Workouts"],
  },
  {
    id: "3",
    name: "Yoga Mat Premium",
    price: 199000,
    description:
      "High-quality non-slip yoga mat perfect for yoga, pilates, and floor exercises in any space.",
    specifications: [
      "Material: TPE (eco-friendly)",
      "Thickness: 6mm",
      'Size: 72" x 24"',
      "Non-slip surface",
      "Weight: 2.5 lbs",
    ],
    benefits: [
      "Superior grip and stability",
      "Eco-friendly material",
      "Easy to clean",
      "Portable with carrying strap",
    ],
    images: [
      "/placeholder.svg?height=400&width=400&text=Yoga+Mat+1",
      "/placeholder.svg?height=400&width=400&text=Yoga+Mat+2",
    ],
    videos: ["/placeholder.svg?height=300&width=400&text=Yoga+Mat+Video"],
    category: "Yoga & Pilates",
    sku: "YM-PREM-003",
    inStock: true,
    isFeatured: false,
    relatedPrograms: [
      "Morning Yoga Flow",
      "Evening Relaxation",
      "Core Stability",
    ],
  },
  {
    id: "4",
    name: "Suspension Trainer",
    price: 449000,
    description:
      "Versatile suspension trainer for bodyweight exercises. Anchor anywhere for a full-body workout.",
    specifications: [
      "Material: Military-grade nylon",
      "Length: Adjustable up to 9 feet",
      "Weight capacity: 350 lbs",
      "Includes door anchor and carabiner",
      "Weight: 2 lbs",
    ],
    benefits: [
      "Bodyweight strength training",
      "Improves balance and flexibility",
      "Portable and lightweight",
      "Suitable for all fitness levels",
    ],
    images: [
      "/placeholder.svg?height=400&width=400&text=Suspension+Trainer+1",
      "/placeholder.svg?height=400&width=400&text=Suspension+Trainer+2",
    ],
    videos: ["/placeholder.svg?height=300&width=400&text=Suspension+Video"],
    category: "Bodyweight Training",
    sku: "ST-001",
    inStock: true,
    isFeatured: true,
    relatedPrograms: [
      "Functional Fitness",
      "Athletic Performance",
      "Balance & Stability",
    ],
  },
  {
    id: "5",
    name: "Foam Roller Pro",
    price: 179000,
    description:
      "High-density foam roller for muscle recovery and myofascial release. Essential for post-workout recovery.",
    specifications: [
      "Material: High-density EVA foam",
      "Length: 18 inches",
      "Diameter: 6 inches",
      "Density: Medium-firm",
      "Weight: 1.5 lbs",
    ],
    benefits: [
      "Improves muscle recovery",
      "Reduces muscle soreness",
      "Increases flexibility",
      "Compact and durable",
    ],
    images: [
      "/placeholder.svg?height=400&width=400&text=Foam+Roller+1",
      "/placeholder.svg?height=400&width=400&text=Foam+Roller+2",
    ],
    videos: ["/placeholder.svg?height=300&width=400&text=Foam+Roller+Video"],
    category: "Recovery",
    sku: "FR-PRO-005",
    inStock: true,
    isFeatured: false,
    relatedPrograms: [
      "Recovery & Mobility",
      "Pre-Workout Prep",
      "Post-Workout Cool Down",
    ],
  },
  {
    id: "6",
    name: "Jump Rope Speed",
    price: 129000,
    description:
      "Professional speed jump rope for cardio workouts. Adjustable length with comfortable handles.",
    specifications: [
      "Material: Steel cable with PVC coating",
      "Handle: Ergonomic foam grip",
      "Length: Adjustable 7-10 feet",
      "Ball bearings for smooth rotation",
      "Weight: 0.5 lbs",
    ],
    benefits: [
      "Excellent cardio workout",
      "Improves coordination",
      "Burns calories efficiently",
      "Minimal space required",
    ],
    images: [
      "/placeholder.svg?height=400&width=400&text=Jump+Rope+1",
      "/placeholder.svg?height=400&width=400&text=Jump+Rope+2",
    ],
    videos: ["/placeholder.svg?height=300&width=400&text=Jump+Rope+Video"],
    category: "Cardio",
    sku: "JR-SPEED-006",
    inStock: true,
    isFeatured: false,
    relatedPrograms: ["Cardio Blast", "HIIT Training", "Coordination Skills"],
  },
  {
    id: "7",
    name: "Kettlebell Adjustable",
    price: 649000,
    description:
      "Adjustable kettlebell with removable weight plates. Perfect for strength and conditioning workouts.",
    specifications: [
      "Weight range: 10-40 lbs",
      "Material: Cast iron with powder coating",
      "Handle: Wide grip design",
      "Includes 6 weight plates",
      "Compact storage design",
    ],
    benefits: [
      "Full-body conditioning",
      "Adjustable weight system",
      "Space-efficient",
      "Durable construction",
    ],
    images: [
      "/placeholder.svg?height=400&width=400&text=Kettlebell+1",
      "/placeholder.svg?height=400&width=400&text=Kettlebell+2",
    ],
    videos: ["/placeholder.svg?height=300&width=400&text=Kettlebell+Video"],
    category: "Free Weights",
    sku: "KB-ADJ-007",
    inStock: true,
    isFeatured: true,
    relatedPrograms: ["Strength & Power", "Functional Training", "Fat Burning"],
  },
  {
    id: "8",
    name: "Balance Board Pro",
    price: 249000,
    description:
      "Wooden balance board for core strengthening and stability training. Great for rehabilitation too.",
    specifications: [
      "Material: Birch plywood",
      "Diameter: 16 inches",
      "Height: 3 inches",
      "Weight capacity: 300 lbs",
      "Non-slip surface",
    ],
    benefits: [
      "Improves balance and coordination",
      "Strengthens core muscles",
      "Enhances proprioception",
      "Injury prevention",
    ],
    images: [
      "/placeholder.svg?height=400&width=400&text=Balance+Board+1",
      "/placeholder.svg?height=400&width=400&text=Balance+Board+2",
    ],
    videos: ["/placeholder.svg?height=300&width=400&text=Balance+Board+Video"],
    category: "Balance & Stability",
    sku: "BB-PRO-008",
    inStock: true,
    isFeatured: false,
    relatedPrograms: ["Balance Training", "Core Stability", "Rehabilitation"],
  },
  {
    id: "9",
    name: "Pull-up Bar Doorway",
    price: 189000,
    description:
      "No-screw doorway pull-up bar that fits most standard door frames. Multiple grip positions available.",
    specifications: [
      "Material: Heavy-duty steel",
      "Fits doors: 24-32 inches wide",
      "Weight capacity: 300 lbs",
      "Multiple grip positions",
      "Foam padding for comfort",
    ],
    benefits: [
      "Upper body strength training",
      "No installation required",
      "Multiple exercise options",
      "Compact storage",
    ],
    images: [
      "/placeholder.svg?height=400&width=400&text=Pull+up+Bar+1",
      "/placeholder.svg?height=400&width=400&text=Pull+up+Bar+2",
    ],
    videos: ["/placeholder.svg?height=300&width=400&text=Pull+up+Bar+Video"],
    category: "Bodyweight Training",
    sku: "PB-DOOR-009",
    inStock: false,
    isFeatured: false,
    relatedPrograms: [
      "Upper Body Strength",
      "Bodyweight Mastery",
      "Muscle Building",
    ],
  },
  {
    id: "10",
    name: "Resistance Loop Bands Set",
    price: 149000,
    description:
      "Set of 5 resistance loop bands with different resistance levels. Perfect for lower body workouts.",
    specifications: [
      "Material: Natural latex",
      "Resistance levels: 5 (X-Light to X-Heavy)",
      "Circumference: 12 inches",
      "Width: 2 inches",
      "Includes carry bag",
    ],
    benefits: [
      "Targets glutes and legs",
      "Progressive resistance",
      "Portable and lightweight",
      "Versatile exercises",
    ],
    images: [
      "/placeholder.svg?height=400&width=400&text=Loop+Bands+1",
      "/placeholder.svg?height=400&width=400&text=Loop+Bands+2",
    ],
    videos: ["/placeholder.svg?height=300&width=400&text=Loop+Bands+Video"],
    category: "Resistance Training",
    sku: "LB-SET-010",
    inStock: true,
    isFeatured: false,
    relatedPrograms: [
      "Glute Activation",
      "Lower Body Strength",
      "Rehabilitation",
    ],
  },
  {
    id: "11",
    name: "Medicine Ball Slam",
    price: 329000,
    description:
      "Heavy-duty medicine ball designed for high-intensity slam exercises. Durable rubber construction.",
    specifications: [
      "Weight: 20 lbs",
      "Material: Durable rubber",
      "Diameter: 9 inches",
      "Textured surface for grip",
      "Bounce-resistant design",
    ],
    benefits: [
      "High-intensity training",
      "Full-body workout",
      "Improves power and strength",
      "Stress relief",
    ],
    images: [
      "/placeholder.svg?height=400&width=400&text=Medicine+Ball+1",
      "/placeholder.svg?height=400&width=400&text=Medicine+Ball+2",
    ],
    videos: ["/placeholder.svg?height=300&width=400&text=Medicine+Ball+Video"],
    category: "Functional Training",
    sku: "MB-SLAM-011",
    inStock: true,
    isFeatured: false,
    relatedPrograms: [
      "HIIT Training",
      "Power Development",
      "Athletic Conditioning",
    ],
  },
  {
    id: "12",
    name: "Pilates Ring",
    price: 119000,
    description:
      "Pilates magic circle for resistance training and muscle toning. Lightweight and portable.",
    specifications: [
      "Material: Flexible steel with padding",
      "Diameter: 14 inches",
      "Padded handles",
      "Weight: 1.5 lbs",
      "Resistance: Medium",
    ],
    benefits: [
      "Tones and strengthens muscles",
      "Improves posture",
      "Enhances flexibility",
      "Low-impact exercise",
    ],
    images: [
      "/placeholder.svg?height=400&width=400&text=Pilates+Ring+1",
      "/placeholder.svg?height=400&width=400&text=Pilates+Ring+2",
    ],
    videos: ["/placeholder.svg?height=300&width=400&text=Pilates+Ring+Video"],
    category: "Yoga & Pilates",
    sku: "PR-RING-012",
    inStock: true,
    isFeatured: false,
    relatedPrograms: [
      "Pilates Fundamentals",
      "Core Toning",
      "Flexibility Training",
    ],
  },
];

export const bundlePackages: BundlePackage[] = [
  {
    id: "morning-energy",
    name: "Morning Energy Pack",
    description: "Start your day right with this energizing workout bundle",
    products: ["1", "3", "6"],
    originalPrice: 627000,
    bundlePrice: 549000,
    image: "/placeholder.svg?height=300&width=400&text=Morning+Energy+Pack",
  },
  {
    id: "desk-warrior",
    name: "Desk Warrior Pack",
    description: "Perfect for office workers who want to stay active",
    products: ["1", "4", "5"],
    originalPrice: 827000,
    bundlePrice: 699000,
    image: "/placeholder.svg?height=300&width=400&text=Desk+Warrior+Pack",
  },
  {
    id: "complete-home-gym",
    name: "Complete Home Gym",
    description: "Everything you need for a complete home workout setup",
    products: ["1", "2", "3", "4", "5"],
    originalPrice: 1925000,
    bundlePrice: 1599000,
    image: "/placeholder.svg?height=300&width=400&text=Complete+Home+Gym",
  },
  {
    id: "strength-builder",
    name: "Strength Builder Pack",
    description: "Build serious strength with this power-focused bundle",
    products: ["2", "7", "11"],
    originalPrice: 1877000,
    bundlePrice: 1549000,
    image: "/placeholder.svg?height=300&width=400&text=Strength+Builder+Pack",
  },
];
